sudo: required
services:
        - docker

before_install:
        - docker build -t tubuntu/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run tubuntu/react-test npm test -- --coverage

after_success:
        - docker build -t tubuntu/multi-client ./client
        - docker build -t tubuntu/multi-nginx ./nginx
        - docker build -t tubuntu/multi-server ./server
        - docker build -t tubuntu/multi-worker ./worker
 # Log in to the docker CLI
        - echo "$DOCKERPW" | docker login -u "$DOCKERID" --password-stdin
 # Take those iamges and push them to Docker hub
        - docker push tubuntu/multi-client
        - docker push tubuntu/multi-nginx
        - docker push tubuntu/multi-server
        - docker push tubuntu/multi-worker

deploy:
        provider: elasticbeanstalk
        region: ap-southeast-1
        app: multi-docker
        env: MultiDocker-env
        bucket_name: elasticbeanstalk-ap-southeast-1-358661719322
        bucket_path: docker-multi
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
                secure: $AWS_SECRET_KEY
